### ISSUE TITLE
move clients__clientid__consentmessages to Auth APIs

### ISSUE THREAD

**Issue by eric-jahn** [hmis-api/2014-hmis-api#3]
APIs https://hmis-api.github.io/2014-hmis-api/#clients__clientid__consentmessages
should be moved to https://github.com/hmis-api/authorization-service-api

**Comment by suryayadavalli** [comment]
Resolved.

https://github.com/hmis-api/2014-hmis-api/commit/a1591437b338a08c425b759678137af3aea38826

https://github.com/hmis-api/authorization-service-api/commit/3dcdc89a0e6847d0ae62fd5901f90fd650b1c8b7
